"use strict";
let places = ['Muree', 'Islamabad', 'Gilgit', 'Hunza Valley '];
console.log('Original' + places);
console.log('Copy' + [...places].sort());
console.log('Original' + places);
console.log('copy' + [...places].sort().reverse());
console.log('Original' + places);
console.log('Original' + places.reverse());
console.log('Original' + places.reverse());
console.log('Original' + places.sort());
console.log('Original' + places.sort().reverse());
